### ISSUE TITLE
Popup opening directly by searching..

### ISSUE THREAD

**Issue by gisveld** [naomap/leaflet-fusesearch#14]
I got the fusesearch working (thanks for this plugin!), with one little problem. When i type in the search bar, the map is already moving to the search results. What i want is that the map waits for the 'click' in the search result screen, and then zoom to the result. I attached my main.js and leaflet.fusesearch.js (i did some minor changes to get it work properly).

Please help.

[main.zip](https://github.com/naomap/leaflet-fusesearch/files/777618/main.zip)

**Comment by naomap** [comment]
The 'minor' change you made to leaflet.fusesearch.js includes this one : 
  map.fitBounds(feature.layer.getBounds(), {'duration': 0.95});
This has been added to createResultItem(), which in invoked to create each item in the result list. This is where you're bug comes from ! 
what were you trying to achieve ?
Antoine.

**Comment by gisveld** [comment]
Hello Antoine,

Thanks for your reaction! I will explain my problem:

- When i downloaded the source files for the first time, i could not get the fusesearch working. The console gives me this bug: TypeError: layer.getPopup is not a function (line 282). So this bug may be already in the source file (leaflet.fusesearch.js).

- When i only change line 282 in: return layer.**open**Popup();    the fusesearch is working but the popup is directly opening by typing. This is not what i want.

- What i want to achieve is a function like your demo on: http://dev.cartocite.fr/CultureNantes/ (the popup opens only by clicking in the search result!).

- I would also be nice that the map zooms to the popup (getBounds) by clicking in the search result.

I have loaded the same fuse.js and leaflet.js source files in my index.html file, just like your CultureNantes-map, so that could not explain this error. I have attached my complete map (with the original fusesearch scource files, only changed the 282 line) . Would u please take a look?

Greetings

[fusesearch.zip](https://github.com/naomap/leaflet-fusesearch/files/782609/fusesearch.zip)
