### ISSUE TITLE
TypeError: jsonFeatures.map is not a function

### ISSUE THREAD

**Issue by thiagoalencargit** [naomap/leaflet-fusesearch#2]
Hi, 
I follow the steps that you put in readme, and got this error:

TypeError: jsonFeatures.map is not a function

Can you help me?

Thanks!

**Comment by naomap** [comment]
I see. Currently indexFeatures() expects the array of features, not the json layer. I should fix the doc, or better let the method accept the json layer or the features array. In the meantime just pass your jsonLayer.features to indexFeatures().

**Comment by thiagoalencargit** [comment]
Awsome, works perfectly. Thank man!

**Comment by naomap** [comment]
Le 08/01/2015 19:19, thiagoalencargit a écrit :
>
> Awsome, works perfectly. Thank man!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/naomap/leaflet-fusesearch/issues/2#issuecomment-69223406>.
>
You're welcome !  I've actually fixed the doc, however I shall let the 
code take care of this and accept either a GeoJSON FeatureCollection or 
an array of Feature's.  Will do that when I get some time ...

Cheers,
Antoine.

**Comment by naomap** [comment]
Fixed by commit ac689f3859ddb9a6afc0217b57f805b1e925ffd8

**Comment by JonahKE** [comment]
Having a similar problem. See details here: http://gis.stackexchange.com/questions/174212/typeerror-jsonfeatures-map-is-not-a-function-using-fuse-search-in-leaflet-js
