### ISSUE TITLE
Show multiple results from the same object

### ISSUE THREAD

**Issue by pufanalexandru** [naomap/leaflet-fusesearch#3]
Hello!

Supposing I have the following geojson file:

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "Name": "Craft",
        "Phone": "0788-912-344",
        "Website": "http://craftpizza.ro/",
        "Menu": [
          {
            "Name": "Craft Mare",
            "Price": 16.5,
            "Weight": 650,
            "Ingredients": "Ham, Bacon, Mozzarella, Ciuperci, Masline, Ardei Gras"
          },
          {
            "Name": "Craft Mica",
            "Price": 11.5,
            "Weight": 450,
            "Ingredients": "Ham, Bacon, Mozzarella, Ciuperci, Masline, Ardei Gras"
          }
        ]
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          22.66456961631775,
          44.63484132461304
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "Name": "Marco Polo",
        "Phone": "0746-575-951",
        "Website": "https://www.facebook.com/MarcoPollo?rf=395662720509344",
        "Menu": [
          {
            "Name": "Taraneasca Mica",
            "Price": 15.9,
            "Weight": 570,
            "Ingredients": "Bacon, Ceapa, Ciuperci"
          }
        ]
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          22.653669118881226,
          44.62586994294029
        ]
      }
    }
  ]
}

Is there any way I can search through feature.properties.Menu.Ingredients, and show multiple results from the same feature if they exist? For example, if I am searching 'Ham', I want to get two results, one for Menu[0] object, and one for Menu[1], both objects of the first feature containing that word.

**Comment by naomap** [comment]
Le 23/03/2015 12:14, pufanalexandru a écrit :
> Is there any way I can search through 
> feature.properties.Menu.Ingredients, and show multiple results from 
> the same feature if they exist? For example, if I am searching 'Ham', 
> I want to get two results, one for Menu[0] object, and one for 
> Menu[1], both objects containing that word.
Hi.

I've never tried this, however there has been some enhancements to the 
Fuse.js library recently that might cover this. You could try indexing 
the features as follows :

searchCtrl.indexFeatures(jsonData.features, ['menu.Ingredients'];

Hmmm ... Actually your data is structured slightly differently to the 
example on Fuse.js (https://github.com/krisk/Fuse), you're using a 
nested array. There is an open issue on Fuse.js that looks related : 
https://github.com/krisk/Fuse/issues/47

I'd suggest you first try to get it to work with Fuse.js alone, then 
we'll figure out how this could be integrated to leaflet-fusesearch.

Regards,
Antoine.

**Comment by naomap** [comment]
Thinking about it, what you're looking for (showing multiple features matching a property value) is a filtering capability, whereas this plugin is about searching a specific feature. This is slightly different and not quite the purpose of this plugin.
Antoine.
