### ISSUE TITLE
find some bug

### ISSUE THREAD

**Issue by denvut** [naomap/leaflet-fusesearch#9]
if in search input on http://dev.cartocite.fr/CultureNantes/
put  number - 8 or 88  we find 
Le Labo 188 Ecole Culturelle, NANTES  -  it' ok

but why if put 888, we find that result too?

**Comment by naomap** [comment]
The plugin provides a "fuzzy" search, it is based on the Fuse.js library. This is why the search returns more than exact matches. Note the threshold option enables you to tune the "fuzziness", a value of 0.0 applies a perfect match.
